spring.application.name=esiusuarios

server.port=8081

spring.datasource.url=jdbc:sqlserver://${DB_HOST:localhost}:1433;databaseName=esiusuarios;encrypt=true;trustServerCertificate=false;
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:TuPasswordAqui}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect