spring.application.name=esiusuarios
server.port=8081

#Comunicación con ESIENTRADAS
esientradas.base-url=${ESIENTRADAS_BASE_URL}
esientradas.api-key=${API_KEY_ESIENTRADAS}

#Correo
correo.username=${EMAIL_USER}
correo.password=${EMAIL_PSWD}

# SQL Server
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA y Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

# Configuración de errores
server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never
server.error.include-exception=false